// Code generated by protoc-gen-go.
// source: gabby.proto
// DO NOT EDIT!

/*
Package gabby is a generated protocol buffer package.

It is generated from these files:
	gabby.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
*/
package gabby

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthResponse_Status int32

const (
	AuthResponse_UNKNOWN     AuthResponse_Status = 0
	AuthResponse_SUCCESS     AuthResponse_Status = 1
	AuthResponse_BADAUTH     AuthResponse_Status = 2
	AuthResponse_REDIRECTION AuthResponse_Status = 3
	AuthResponse_RETRYSOON   AuthResponse_Status = 4
	AuthResponse_SERVERQUIT  AuthResponse_Status = 5
)

var AuthResponse_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "SUCCESS",
	2: "BADAUTH",
	3: "REDIRECTION",
	4: "RETRYSOON",
	5: "SERVERQUIT",
}
var AuthResponse_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"SUCCESS":     1,
	"BADAUTH":     2,
	"REDIRECTION": 3,
	"RETRYSOON":   4,
	"SERVERQUIT":  5,
}

func (x AuthResponse_Status) String() string {
	return proto.EnumName(AuthResponse_Status_name, int32(x))
}
func (AuthResponse_Status) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type AuthRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Secret string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type AuthResponse struct {
	Status     AuthResponse_Status `protobuf:"varint,1,opt,name=status,enum=gabby.AuthResponse_Status" json:"status,omitempty"`
	RedirectTo string              `protobuf:"bytes,31,opt,name=redirect_to,json=redirectTo" json:"redirect_to,omitempty"`
	RetryDelay int32               `protobuf:"varint,41,opt,name=retry_delay,json=retryDelay" json:"retry_delay,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetStatus() AuthResponse_Status {
	if m != nil {
		return m.Status
	}
	return AuthResponse_UNKNOWN
}

func (m *AuthResponse) GetRedirectTo() string {
	if m != nil {
		return m.RedirectTo
	}
	return ""
}

func (m *AuthResponse) GetRetryDelay() int32 {
	if m != nil {
		return m.RetryDelay
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "gabby.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "gabby.AuthResponse")
	proto.RegisterEnum("gabby.AuthResponse_Status", AuthResponse_Status_name, AuthResponse_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Server service

type ServerClient interface {
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/gabby.Server/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Server service

type ServerServer interface {
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gabby.Server/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gabby.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Server_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gabby.proto",
}

func init() { proto.RegisterFile("gabby.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0x86, 0x9b, 0x7c, 0x6d, 0x3e, 0x3a, 0xd1, 0xba, 0x8c, 0x20, 0xa1, 0x97, 0x96, 0x9c, 0xea,
	0xa5, 0x60, 0xc5, 0x93, 0xa7, 0x9a, 0x2c, 0x18, 0x84, 0x04, 0x77, 0x13, 0xc5, 0x53, 0x48, 0x9a,
	0x45, 0x03, 0x62, 0xea, 0xee, 0x46, 0xc8, 0x0f, 0xf6, 0x7f, 0x48, 0x36, 0x15, 0x14, 0x3c, 0x3e,
	0x2f, 0xcf, 0xcc, 0xf0, 0x0e, 0xb8, 0xcf, 0x45, 0x59, 0x76, 0xeb, 0xbd, 0x6c, 0x74, 0x83, 0x13,
	0x03, 0xfe, 0x15, 0xb8, 0xdb, 0x56, 0xbf, 0x30, 0xf1, 0xde, 0x0a, 0xa5, 0x71, 0x06, 0x76, 0x5d,
	0x79, 0xd6, 0xd2, 0x5a, 0x4d, 0x99, 0x5d, 0x57, 0x78, 0x06, 0x8e, 0x12, 0x3b, 0x29, 0xb4, 0x67,
	0x9b, 0xec, 0x40, 0xfe, 0xa7, 0x05, 0x47, 0xc3, 0x9c, 0xda, 0x37, 0x6f, 0x4a, 0xe0, 0x06, 0x1c,
	0xa5, 0x0b, 0xdd, 0x2a, 0x33, 0x3c, 0xdb, 0xcc, 0xd7, 0xc3, 0xb1, 0x9f, 0xd2, 0x9a, 0x1b, 0x83,
	0x1d, 0x4c, 0x5c, 0x80, 0x2b, 0x45, 0x55, 0x4b, 0xb1, 0xd3, 0xb9, 0x6e, 0xbc, 0x85, 0xb9, 0x00,
	0xdf, 0x51, 0xda, 0x0c, 0x82, 0x96, 0x5d, 0x5e, 0x89, 0xd7, 0xa2, 0xf3, 0xce, 0x97, 0xd6, 0x6a,
	0xd2, 0x0b, 0x5a, 0x76, 0x61, 0x9f, 0xf8, 0x39, 0x38, 0xc3, 0x4e, 0x74, 0xe1, 0x7f, 0x16, 0xdf,
	0xc5, 0xc9, 0x63, 0x4c, 0x46, 0x3d, 0xf0, 0x2c, 0x08, 0x28, 0xe7, 0xc4, 0xea, 0xe1, 0x66, 0x1b,
	0x6e, 0xb3, 0xf4, 0x96, 0xd8, 0x78, 0x02, 0x2e, 0xa3, 0x61, 0xc4, 0x68, 0x90, 0x46, 0x49, 0x4c,
	0xfe, 0xe1, 0x31, 0x4c, 0x19, 0x4d, 0xd9, 0x13, 0x4f, 0x92, 0x98, 0x8c, 0x71, 0x06, 0xc0, 0x29,
	0x7b, 0xa0, 0xec, 0x3e, 0x8b, 0x52, 0x32, 0xd9, 0x5c, 0x83, 0xc3, 0x85, 0xfc, 0x10, 0x12, 0x2f,
	0x60, 0xdc, 0x77, 0x41, 0xfc, 0x55, 0xcc, 0x7c, 0x6d, 0x7e, 0xfa, 0x47, 0x59, 0x7f, 0x54, 0x3a,
	0xe6, 0xd3, 0x97, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x95, 0xbb, 0x75, 0xe4, 0x78, 0x01, 0x00,
	0x00,
}
